#!/usr/bin/env bash
set -euo pipefail

output_file=".docker/ports.env"
mkdir -p "$(dirname "$output_file")"

compose_port() {
  local service="$1"
  local container_port="$2"
  local host_port

  host_port="$(docker compose port "$service" "$container_port" | awk -F: 'NF { print $NF; exit }')"
  if [[ -z "$host_port" ]]; then
    printf 'No published host port found for %s:%s\n' "$service" "$container_port" >&2
    exit 1
  fi

  printf '%s' "$host_port"
}

api_port="$(compose_port api 8000)"
postgres_port="$(compose_port postgres 5432)"
redis_port="$(compose_port redis 6379)"
minio_port="$(compose_port minio 9000)"
minio_console_port="$(compose_port minio 9001)"

{
  printf '# Generated by make docker-run; source this file for host access.\n'
  printf 'export UGC_API_PORT=%s\n' "$api_port"
  printf 'export UGC_API_BASE_URL=http://127.0.0.1:%s\n' "$api_port"
  printf 'export UGC_POSTGRES_PORT=%s\n' "$postgres_port"
  printf 'export UGC_REDIS_PORT=%s\n' "$redis_port"
  printf 'export UGC_MINIO_PORT=%s\n' "$minio_port"
  printf 'export UGC_MINIO_CONSOLE_PORT=%s\n' "$minio_console_port"
} > "$output_file"

printf 'Captured host ports in %s\n' "$output_file"
cat "$output_file"
